# 2. NumPy 배열
* NumPy에는 **ndarray**라는 데이터 타입의 배열이 사용된다.
* 같은 타입의 데이터만 저장할 수 있다.
* Python list에 비해 계산 속도가 빠르다.

In [24]:
import numpy as np

## 2-1. np.array() 함수로 생성하기

### 1차원 배열 생성하기

In [25]:
# 1차원 배열 생성하기
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [26]:
# type확인
type(arr)

numpy.ndarray

In [27]:
#overflow 테스트
arr = np.array([1474836490000000001, 2, 3, 4], dtype=np.int64)
arr

array([1474836490000000001,                   2,                   3,
                         4], dtype=int64)

In [28]:
arr = np.array([1,2,3,4],dtype=float)
arr

array([1., 2., 3., 4.])

In [29]:
arr.dtype

dtype('float64')

In [30]:
# shape : 각 차원의 배열의 size(차원의 모양)
arr.shape


(4,)

In [31]:
# size : 배열 전체의 요소의 갯수
arr.size

4

In [32]:
# ndim : 차원의 수
arr.ndim

1

In [33]:
# ndarray에는 같은 데이터 타입만 들어가야 함
arr = np.array([1,2,3,3.14], dtype=int)
arr.dtype

dtype('int32')

In [34]:
# int, float, string -> string
# >(big-endian), <(little-endian) 
# 32-character string
arr = np.array([1,2.13,'1213'])
arr.dtype

dtype('<U32')

In [35]:
# 기존의 배열을 이용하여 타입이 다른 배열을 생성하기
new_arr = arr.astype(float)
new_arr

array([1.000e+00, 2.130e+00, 1.213e+03])

In [36]:
arr.dtype, new_arr.dtype

(dtype('<U32'), dtype('float64'))

### 2차원 배열 생성하기

In [37]:
arr2 = np.array([[1,2,3,4],
                [6,7,8,9],
                [10,11,12,13],
                [14,15,16,17]])
arr2

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [38]:
new_arr2 = arr2.astype(int)
new_arr2

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

## 2-2. np.arange() 함수로 생성하기

### 1차원 배열 생성하기

In [39]:
for i in range(1,11, 2):  # 1,3,5,7,9
    print(i)

1
3
5
7
9


In [40]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

### 2차원 배열 생성하기

In [41]:
arr = np.arange(12) # 0,11
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
new_arr = arr.reshape((1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,12)) #shape
new_arr

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 0,
                                       1,
                                       2,
                                       3,
                                       4,
                                       5,
                                       6,
                                       7,
                                       8,
                                       9,
                                      10,
                                      11]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
arr.shape = (3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수로 생성

In [46]:
arr = np.ones((3,4,4), dtype = int)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

## 2-5. np.linspace() 함수로 생성

In [47]:
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [68]:
arr = np.linspace(0, 10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [69]:
arr.shape

(50,)

In [50]:
# (5,10)인 2차원 배열로 만들기
arr2 = arr.reshape((5,10))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

## 2-6. np.full() 함수로 생성

In [51]:
arr2 = np.full((3,4), 1)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## 2-7. np.eye() 함수로 생성

In [77]:
#단위 행렬, 항등 행렬
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

## 2-8. np.random으로 생성

In [53]:
arr = np.random.randint(100, size=5)
arr

array([77, 40, 93, 46, 39])

In [84]:
np.random.seed()
np.random.rand(2,3)

AttributeError: module 'numpy.random' has no attribute 'ranint'

## 2-9. NumPy 배열 save & Load

In [55]:
arr = np.arange(0,5) 
arr

array([0, 1, 2, 3, 4])

In [56]:
np.save('my_arr', arr)

In [57]:
new_arr = np.load('my_arr.npy')

In [58]:
new_arr

array([0, 1, 2, 3, 4])