# 3. 연산

## 3-1. 산술연산

In [1]:
import numpy as np

In [2]:
# 1차원 배열
a = np.arange(1,5)
b = np.arange(5,9)

In [3]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [4]:
#shape이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [5]:
a - b

array([-4, -4, -4, -4])

In [6]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [7]:
# 2차원 배열
a = np.arange(1,9).reshape(2,4)
b = np.arange(7,15).reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a+b

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [9]:
# 단순 곱셈 (별로 안쓰임)
a*b

array([[  7,  16,  27,  40],
       [ 55,  72,  91, 112]])

### 행렬의 곱셈 (dot product)

In [10]:
b = np.arange(7,15).reshape(4,2)
a,b

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14]]))

In [11]:
np.dot(a,b)

array([[110, 120],
       [270, 296]])

In [12]:
a.dot(b)

array([[110, 120],
       [270, 296]])

In [13]:
a + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 3-2.Aggregation 함수

### 1차원 배열

In [15]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [16]:
# max값 찾기
np.max(a)

5

In [17]:
# min값 찾기
np.min(a)

1

In [18]:
a.max(), a.min()

(5, 1)

In [19]:
# sum값 구하기
np.sum(a)

15

In [20]:
# 평균값 구하기
np.mean(a)

3.0

In [21]:
b = np.array([1,2,3,4,100]) # 이상치(outlier)
b

array([  1,   2,   3,   4, 100])

In [22]:
# 중앙값(median)
np.median(b)

3.0

In [23]:
# 데이터가 짝수개인 경우
b = np.array([1,3,5,100])
np.median(b)

4.0

In [24]:
# 표준편자(standard deviation)
np.std(a)

1.4142135623730951

### 2차원 배열

In [25]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.max(a), a.max()

(6, 6)

In [27]:
np.min(a), a.min()

(1, 1)

In [28]:
# 2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a, axis=0)  # 행(row)

array([4, 5, 6])

In [29]:
np.max(a, axis=1) # 열(column)

array([3, 6])

In [30]:
# cumsum, corrcoef(상관계수) 구하기
np.cumsum(a) # 누적

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [31]:
#corrcoef (상관계수)
# 키와 몸무게의 상관관계
h = [160, 165, 170, 180]
w = [47, 55, 70, 85]
np.corrcoef(h,w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [47]:
np.std(h)

7.39509972887452

In [32]:
ha = np.mean(h)
wa = np.mean(w)
ha,wa

(168.75, 64.25)

In [48]:
a = np.sqrt(np.sum((h - ha)**2)/4)
b = np.sqrt(np.sum((w - wa)**2)/4)
a,b

(7.39509972887452, 14.549484526951462)

In [34]:
c = np.sum((h - wa) * (w - wa))
c

426.25

In [35]:
r = c/(a*b)
r

0.990404850180661

### 비교 (Comparison)

In [36]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [37]:
a >= 3

array([False, False,  True,  True,  True])

In [38]:
a + 3

array([4, 5, 6, 7, 8])

In [39]:
a == 3

array([False, False,  True, False, False])