# 4. 정렬

## 4-1. 1차원 배열

In [1]:
import numpy as np

In [2]:
np.random.seed(100)
arr = np.random.randint(1, 10, size=10)
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [14]:
# 오름차순 정렬
np.sort(arr)

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [4]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([9, 9, 8, 8, 6, 5, 4, 3, 3, 1])

In [5]:
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

## 4-2. 2차원 배열

In [6]:
arr2 = np.random.randint(1,10, size=(3,4))
arr2

array([[3, 3, 2, 1],
       [9, 5, 1, 7],
       [3, 5, 2, 6]])

In [7]:
np.sort(arr2)

array([[1, 2, 3, 3],
       [1, 5, 7, 9],
       [2, 3, 5, 6]])

In [8]:
np.sort(arr2, axis=0)

array([[3, 3, 1, 1],
       [3, 5, 2, 6],
       [9, 5, 2, 7]])

In [9]:
arr2

array([[3, 3, 2, 1],
       [9, 5, 1, 7],
       [3, 5, 2, 6]])

In [10]:
# index를 반환하는 argsort
np.argsort(arr2)

array([[3, 2, 0, 1],
       [2, 1, 3, 0],
       [2, 0, 1, 3]], dtype=int64)

In [16]:
np.argsort(arr2, axis=0)

array([[0, 0, 1, 0],
       [2, 1, 0, 2],
       [1, 2, 2, 1]], dtype=int64)