# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[0], arr[-1], arr[4]

(0, 9, 4)

In [5]:
arr2 = np.arange(1, 13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr2[0][1], arr2[1][2], arr2[2][3]

(2, 7, 12)

In [7]:
arr2[0, 1], arr2[1, 2], arr2[2, 3]

(2, 7, 12)

In [8]:
arr2[-1,-2]

11

## 5-2. 슬라이싱

### 1차원 배열

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 2~ 끝
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 슬라이싱을 한 후에 값을 변경하면 원본에 영향을 미칠까?
new_arr = arr[:5]
new_arr

array([0, 1, 2, 3, 4])

In [12]:
new_arr[0] = 100
new_arr

array([100,   1,   2,   3,   4])

In [13]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

### 2차원 배열

In [14]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# 첫번째 행을 모두 가져오기
arr2[0,0:]

array([1, 2, 3, 4])

In [16]:
# 세번째 행을 모두 가져오기
arr2[1:2,:]

array([[5, 6, 7, 8]])

## 5-3. Fancy 인덱싱

In [17]:
# 1차원 배열
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr[0:6:2]

array([1, 3, 5])

In [19]:
# Fancy 인덱싱
arr[[0,2,4]]

array([1, 3, 5])

In [20]:
# 2차원 배열 
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np.array([arr2[0],arr2[2]])

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [29]:
# Fancy 인덱싱
arr2[[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [23]:
arr2[0, 2]

3

## 5-4. Boolean 인덱싱

In [24]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [25]:
#cond = [False, False, False, True, False]
arr[[False, True, False, False, False]]

array([1])

In [26]:
arr[arr>2]

array([3, 4])

In [27]:
arr[arr % 2 == 0]

array([0, 2, 4])