# 6. 실습

In [2]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [3]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr.dtype, np.shape(arr), arr.size

NameError: name 'arr' is not defined

In [ ]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.array([[10,20,30,40],[50,60,70,80]])
arr2

In [5]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [6]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
arr2 = np.arange(10,82,10)
arr2.reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [7]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.randint(7, size=100)

array([3, 5, 0, 4, 3, 4, 1, 3, 3, 2, 0, 2, 0, 4, 4, 5, 4, 0, 2, 4, 2, 5,
       1, 1, 2, 6, 2, 6, 5, 5, 6, 6, 0, 6, 0, 4, 4, 6, 3, 3, 4, 3, 5, 1,
       5, 3, 3, 5, 2, 2, 2, 6, 1, 5, 6, 3, 2, 2, 2, 5, 2, 1, 2, 4, 1, 1,
       3, 0, 2, 0, 5, 1, 6, 2, 3, 5, 5, 2, 6, 1, 2, 5, 6, 4, 0, 6, 2, 6,
       0, 4, 2, 3, 1, 3, 6, 5, 6, 5, 6, 0])

In [8]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
np.random.rand(3,4)

array([[0.70570096, 0.27094816, 0.22766037, 0.84385031],
       [0.75993906, 0.76105706, 0.91807207, 0.41710427],
       [0.29547961, 0.99000413, 0.8980781 , 0.68303003]])

## 6-2. 산술연산

In [9]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)
arr1, arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [10]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
arr1, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [12]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
np.add(arr1, arr2)
arr1 - arr2

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [13]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2 = arr2.reshape(5,2)
arr1 = arr1.reshape(2,5)

In [14]:
# 행렬곱셈(dot product) 연산하기
np.dot(arr1,arr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [15]:
# 1~10까지 이루어진 1차원 배열 생성하기
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# 최대값, 최소값 출력하기
arr.max()
arr.min()

1

In [17]:
# 배열요소의 합, 평균값 출력하기
arr.sum()
arr.mean()

5.5

In [18]:
# 중앙값(중위값), 표준편차 출력하기
np.median(arr), np.std(arr)

(5.5, 2.8722813232690143)

In [19]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
# 각 행의 max값, min값 출력하기
np.max(arr2, axis=0)
np.min(arr2, axis=0)

array([1, 2, 3, 4, 5])

In [21]:
# 각 열의 max값, min값 출력하기
np.max(arr2, axis=0)
np.max(arr2, axis=1)

array([ 5, 10, 15, 20])

In [22]:
# 각 행의 sum값 출력하기
np.sum(arr2, axis=0)

array([34, 38, 42, 46, 50])

In [23]:
# 각 열의 sum값 출력하기
np.sum(arr2, axis=1)

array([15, 40, 65, 90])

## 6-4. 정렬

In [24]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint(100,size=10)

In [25]:
# 위 1차원 배열을 오름차순 정렬하기
np.sort(arr)

array([ 8, 10, 24, 48, 52, 67, 79, 87, 94, 98])

In [26]:
# 위 1차원 배열을 내림차순 정렬하기
np.sort(arr)[::-1]

array([98, 94, 87, 79, 67, 52, 48, 24, 10,  8])

In [27]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
arr2 = np.random.randint(100,size=(5,10))
np.random.seed(100)
arr2

array([[53, 66, 98, 14, 34, 24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27,  4, 31,  1, 13, 83],
       [ 4, 91, 59, 67,  7, 49, 47, 65, 61, 14],
       [55, 71, 80,  2, 94, 19, 98, 63, 53, 27],
       [56, 30, 48, 47, 39, 38, 44, 18, 64, 56]])

In [28]:
# 열 기준 정렬하기
np.sort(arr2,axis=0)

array([[ 4, 30, 48,  2,  7,  4, 15,  1, 13, 14],
       [ 9, 66, 59,  2, 27, 19, 31, 18, 53, 16],
       [53, 71, 80, 14, 34, 24, 44, 60, 58, 27],
       [55, 91, 86, 47, 39, 38, 47, 63, 61, 56],
       [56, 93, 98, 67, 94, 49, 98, 65, 64, 83]])

In [29]:
# 행 기준 정렬하기
np.sort(arr2,axis=1)

array([[14, 15, 16, 24, 34, 53, 58, 60, 66, 98],
       [ 1,  2,  4,  9, 13, 27, 31, 83, 86, 93],
       [ 4,  7, 14, 47, 49, 59, 61, 65, 67, 91],
       [ 2, 19, 27, 53, 55, 63, 71, 80, 94, 98],
       [18, 30, 38, 39, 44, 47, 48, 56, 56, 64]])

## 6-5. 인덱싱과 슬라이싱

In [30]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
# 위 배열에서 7을 인덱싱하기
arr[1][2]

7

In [32]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr[2, 4]

14

In [51]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr[1,1:3]

array([6, 7])

In [52]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr[1:,2:4]

array([[ 7,  8],
       [12, 13]])

In [53]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr[:2,3:]

array([[3, 4],
       [8, 9]])

In [54]:
# 위 배열에서 3의 배수 찾기
arr[arr%3==0]

array([ 0,  3,  6,  9, 12])

In [55]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr[arr % 4 ==1]

array([ 1,  5,  9, 13])

In [60]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr[(arr%3==0)&(arr % 4 ==1)]

array([9])